Repository seat-checking/back-end, pull requests merged in 2023-07, with the labels that each got.

#55 어드민 가게 형태 조회
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreChairRepository.java
  src/main/java/project/seatsence/src/store/dao/StoreSpaceRepository.java
  src/main/java/project/seatsence/src/store/dao/StoreTableRepository.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreChairResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreFormResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreTableResponse.java
  src/main/java/project/seatsence/src/store/service/StoreChairService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/main/java/project/seatsence/src/store/service/StoreTableService.java
Labels: feature, review-needed

#60 AdminAdapter, AdminAdapterImpl 추가
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/admin/service/AdminAdapter.java
  src/main/java/project/seatsence/src/admin/service/AdminAdapterImpl.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
Labels: refactoring, review-needed

#61 AccessToken 발급 기능 구현
  build.gradle
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/filter/CustomAuthenticationFilter.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthFailureHandler.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthSuccessHandler.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthenticationProvider.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/global/config/security/TokenUtils.java
  src/main/java/project/seatsence/global/config/security/WebSecurityConfig.java
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/global/token/CustomAuthenticationToken.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dto/CustomUserDetailsDto.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignInRequest.java
  src/main/java/project/seatsence/src/user/dto/response/UserSignInResponse.java
  src/main/java/project/seatsence/src/user/service/CustomUserDetailsService.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
Labels: feature

#63 Store Entity <-> AdminInfo Entity 연결
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreCreateRequest.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: feature, review-needed

#64 Refresh Token 개발 완료 및 관련 인증, 인가 구현 완료
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthSuccessHandler.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthenticationProvider.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/global/config/security/TokenUtils.java
  src/main/java/project/seatsence/global/config/security/WebSecurityConfig.java
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/global/converter/StateAttributeConverter.java
  src/main/java/project/seatsence/global/entity/BaseTimeAndStateEntity.java
  src/main/java/project/seatsence/src/auth/dao/RefreshTokenRepository.java
  src/main/java/project/seatsence/src/auth/domain/JwtState.java
  src/main/java/project/seatsence/src/auth/domain/RefreshToken.java
  src/main/java/project/seatsence/src/auth/domain/TokenType.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/dto/CustomUserDetailsDto.java
  src/main/java/project/seatsence/src/user/dto/response/UserSignInResponse.java
  src/main/java/project/seatsence/src/user/service/CustomUserDetailsService.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
  src/main/java/project/seatsence/src/user/service/UserSignUpService.java
Labels: feature, fix, review-needed

#66 Spring Security 허용 자원 추가
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
Labels: fix

#68 토큰 만료기한 수정
  src/main/java/project/seatsence/global/config/filter/CustomAuthenticationFilter.java
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthenticationProvider.java
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/resources/application.yml
Labels: fix

#69 사용자 가게 이름 검색 시 정렬조건 밑 페이징 적용
  src/main/java/project/seatsence/global/entity/BaseTimeAndStateEntity.java
  src/main/java/project/seatsence/src/admin/domain/AdminInfo.java
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreRepository.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
  src/test/java/project/seatsence/src/store/service/StoreServiceTest.java
Labels: feature, review-needed

#72 일치하는 email의 user 검색 API 구현 완료
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dto/request/FindUserByEmailRequest.java
  src/main/java/project/seatsence/src/user/dto/response/FindUserByEmailResponse.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
Labels: feature

#74 기획변경에 따라 회원가입시 실명받도록 수정작업 완료
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignUpRequest.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/domain/User.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignUpRequest.java
  src/main/java/project/seatsence/src/user/dto/response/FindUserByEmailResponse.java
  src/main/java/project/seatsence/src/user/service/CustomUserDetailsService.java
  src/main/java/project/seatsence/src/user/service/UserService.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
Labels: fix, review-needed

#77 순환 참조 해결
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/src/user/service/UserDetailsServiceImpl.java
Labels: hotfix, review-needed

#78 관리자 가게 형태 등록 및 조회 API 수정
  src/main/java/project/seatsence/src/store/domain/StoreChair.java
  src/main/java/project/seatsence/src/store/domain/StoreTable.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreFormCreateRequest.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreChairResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreTableResponse.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: fix, review-needed

#84 Spring Security로 인해, Swagger에서 발생하는 'Failed to load remote configuration' 해결
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
Labels: bug, review-needed

#86 보안을 위해 Refresh Token을 Cookie에서 활용하도록 수정
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dto/response/UserSignInResponse.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: enhancement, review-needed

#88 관리자 로그인 API 구현
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminSignInResponse.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
Labels: feature, review-needed

#92 관리자 로그인 response 수정
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminSignInResponse.java
Labels: hotfix

#94 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#93 관리자 새로운 가게 등록시 StoreMember(OWNER) 추가
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/StoreMember.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/user/domain/User.java
  src/test/java/project/seatsence/src/store/service/StoreServiceTest.java
Labels: feature, review-needed

#96 유저 로그인 API에서 UserRole이 USER인지 체크하는 검증 로직 추가
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: fix

#99 관리자 로그인 API 권한 응답 추가
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminSignInResponse.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/domain/StoreMember.java
Labels: feature, review-needed

#101 유저 Store 정보 조회 시 영업 여부 필드 추가
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/domain/Day.java
  src/main/java/project/seatsence/src/store/dto/response/StoreListResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: feature

#102 Adapter 관련 코드 삭제 및 수정
  src/main/java/project/seatsence/src/admin/service/AdminAdapter.java
  src/main/java/project/seatsence/src/admin/service/AdminAdapterImpl.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/user/service/UserAdaptor.java
  src/main/java/project/seatsence/src/user/service/UserAdaptorImpl.java
  src/test/java/project/seatsence/src/store/service/StoreServiceTest.java
Labels: refactoring, review-needed

#104 스페이스 예약 구분에 따른 스페이스 생성 API 수정
  src/main/java/project/seatsence/global/utils/EnumUtils.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/ReservationUnit.java
  src/main/java/project/seatsence/src/store/domain/StoreSpace.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreFormCreateRequest.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: feature, review-needed

#105 유저 좌석 예약 기능 구현 완료
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/reservation/api/ReservationApi.java
  src/main/java/project/seatsence/src/reservation/dao/ReservationRepository.java
  src/main/java/project/seatsence/src/reservation/domain/Reservation.java
  src/main/java/project/seatsence/src/reservation/dto/request/SeatReservationRequest.java
  src/main/java/project/seatsence/src/reservation/service/SeatReservationService.java
  src/main/java/project/seatsence/src/store/dao/StoreChairRepository.java
  src/main/java/project/seatsence/src/store/domain/StoreMember.java
  src/main/java/project/seatsence/src/store/service/StoreChairService.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/domain/User.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: feature

#109 스페이스 <-> 좌석 Entity 연결에 따른 스페이스 생성 API 수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/StoreChair.java
  src/main/java/project/seatsence/src/store/domain/StoreTable.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: fix, review-needed

#110 스페이스 예약 기능 구현 및 예약 기능에 유효성 검사 로직 추가
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/src/auth/dao/RefreshTokenRepository.java
  src/main/java/project/seatsence/src/reservation/api/ReservationApi.java
  src/main/java/project/seatsence/src/reservation/dto/request/SpaceReservationRequest.java
  src/main/java/project/seatsence/src/reservation/service/ReservationService.java
  src/main/java/project/seatsence/src/reservation/service/SeatReservationService.java
  src/main/java/project/seatsence/src/store/dao/StoreChairRepository.java
  src/main/java/project/seatsence/src/store/dao/StoreSpaceRepository.java
  src/main/java/project/seatsence/src/store/domain/StoreChair.java
  src/main/java/project/seatsence/src/store/domain/StoreTable.java
  src/main/java/project/seatsence/src/store/service/StoreChairService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: enhancement, feature, review-needed

#113 관리자의 예약 관리를 위해, ReservationStatus enum 생성 및 예약시 기본값으로 PENDING이 들어가도록 수정
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/src/reservation/api/ReservationApi.java
  src/main/java/project/seatsence/src/reservation/domain/Reservation.java
  src/main/java/project/seatsence/src/reservation/domain/ReservationStatus.java
  src/main/java/project/seatsence/src/reservation/service/ReservationService.java
Labels: enhancement, feature

#118 클라리언트에서 쿠키 요청시 CORS발생하는 이슈 해결을 위해, allowCredentials를 true로 설정
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/src/reservation/service/ReservationService.java
Labels: bug

#120 쿠키 사용시 발생하는 CORS 해결을 위해, exposedHeaders 추가
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
Labels: bug
