Repository seat-checking/back-end, pull requests merged in 2023-06, with the labels that each got.

#2 API response 형식 통일
  src/main/java/project/seatsence/common/code/ResponseCode.java
  src/main/java/project/seatsence/common/response/BaseResponse.java
Labels: chore, review-needed

#6 Swagger적용 및 Spotless
  build.gradle
  src/main/java/project/seatsence/SeatSenceApplication.java
  src/main/java/project/seatsence/common/code/ResponseCode.java
  src/main/java/project/seatsence/common/config/SwaggerConfig.java
  src/main/java/project/seatsence/common/response/BaseResponse.java
  src/main/resources/application.yml
  src/test/java/project/seatsence/SeatSenceApplicationTests.java
Labels: chore, review-needed

#8 BaseEntity 및 ErrorResponse 생성
  src/main/java/project/seatsence/SeatSenceApplication.java
  src/main/java/project/seatsence/global/Entity/BaseEntity.java
  src/main/java/project/seatsence/global/Entity/BaseTimeAndStateEntity.java
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/SwaggerConfig.java
  src/main/java/project/seatsence/global/converter/StateAttributeConverter.java
  src/main/java/project/seatsence/global/response/BaseResponse.java
  src/main/java/project/seatsence/global/response/ErrorResponse.java
Labels: feature, review-needed

#9 jpa 네이밍전략 수정 및 ApplicationTest코드 ActiveProfile 설정
  src/main/java/project/seatsence/global/Entity/BaseEntity.java
  src/main/java/project/seatsence/global/Entity/BaseTimeAndStateEntity.java
  src/main/java/project/seatsence/global/converter/StateAttributeConverter.java
  src/main/java/project/seatsence/global/response/BaseResponse.java
  src/main/java/project/seatsence/global/response/ErrorResponse.java
  src/main/resources/application.yml
  src/test/java/project/seatsence/SeatSenceApplicationTests.java
Labels: fix, review-needed

#12 EC2 서버에서 코드 가동시 발생하는 에러 해결을 위해 프로파일 관리 방법 변경
  src/main/resources/application.yml
Labels: bug

#14 EC2에서 빌드 후 실행시, 사용하는 DB 명시하지 않아 발생하는 에러 해결
  src/main/resources/application.yml
Labels: bug, review-needed

#16 [WiP]converter의 ACTIVE 오타 수정
  src/main/java/project/seatsence/global/converter/StateAttributeConverter.java
Labels: bug, fix

#26 유저 로그인 API 구현 및 유저 로그인,회원가입 API 응답값 생성 및 spring security 설정값 수정
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
  src/main/java/project/seatsence/global/exceptions/BaseException.java
  src/main/java/project/seatsence/global/jwt/JwtTokenProvider.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dao/UserAdaptor.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/dao/UserRepositoryCustom.java
  src/main/java/project/seatsence/src/user/domain/User.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignInRequest.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignUpRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateEmailRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateNicknameRequest.java
  src/main/java/project/seatsence/src/user/dto/response/UserSignInResponse.java
  src/main/java/project/seatsence/src/user/dto/response/UserSignUpResponse.java
  src/main/java/project/seatsence/src/user/service/UserSignInService.java
  src/main/java/project/seatsence/src/user/service/UserSignUpService.java
Labels: feature, refactoring, review-needed

#23 관리자 가게 정보 가져오기
  build.gradle
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/converter/StateAttributeConverter.java
  src/main/java/project/seatsence/global/mapper/GenericMapper.java
  src/main/java/project/seatsence/global/util/EnumUtils.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreRepository.java
  src/main/java/project/seatsence/src/store/domain/Category.java
  src/main/java/project/seatsence/src/store/domain/Day.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/StoreMapper.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/resources/application.yml
  src/test/java/project/seatsence/src/store/service/StoreServiceTest.java
Labels: feature, review-needed

#34 토큰 환경 변수 수정 및 JWT yml 추가
  src/main/java/project/seatsence/global/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: bug, fix

#50 어드민 회원가입 API 코드 리펙토링
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dao/AdminRepository.java
  src/main/java/project/seatsence/src/admin/domain/AdminInfo.java
  src/main/java/project/seatsence/src/admin/service/AdminSignUpService.java
Labels: fix, refactoring, review-needed

#53 관리자 사업자 등록번호 추가 API 구현, 테이블 컬럼명 수정
  src/main/java/project/seatsence/global/annotation/ValidBusinessRegistrationNumber.java
  src/main/java/project/seatsence/global/annotation/ValidNickname.java
  src/main/java/project/seatsence/global/annotation/validator/BusinessRegistrationNumberValidator.java
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dao/AdminRepository.java
  src/main/java/project/seatsence/src/admin/domain/AdminInfo.java
  src/main/java/project/seatsence/src/admin/dto/request/AdminNewBusinessInformationRequest.java
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignUpRequest.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminNewBusinessInformationResponse.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
Labels: feature, fix, review-needed

#54 관리자 user-id 경로 변수명 수정
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
Labels: bug
