Repository seat-checking/back-end, pull requests merged in 2023-10, with the labels that each got.

#286 가게 기본 정보 등록 및 확인 시 전화번호 필드 추가
  src/main/java/project/seatsence/src/store/api/admin/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/api/user/UserStoreApi.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/admin/basic/StoreBasicInformationRequest.java
  src/main/java/project/seatsence/src/store/dto/response/admin/basic/StoreBasicInformationResponse.java
  src/main/java/project/seatsence/src/store/dto/response/user/StoreDetailResponse.java
  src/main/java/project/seatsence/src/store/dto/response/user/StoreListResponse.java
Labels: feature

#287 가게 기본 정보 등록 시 origin image 없이도 저장되도록 required false 옵션 추가
  src/main/java/project/seatsence/src/store/api/admin/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/service/S3Service.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: hotfix

#288 가게의 스페이스 참여 가능한 리스트 API
  src/main/java/project/seatsence/global/response/SliceResponse.java
  src/main/java/project/seatsence/src/utilization/api/participation/ParticipationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/dao/walkin/WalkInRepository.java
  src/main/java/project/seatsence/src/utilization/domain/Utilization.java
  src/main/java/project/seatsence/src/utilization/dto/response/participation/StoreParticipationListResponse.java
  src/main/java/project/seatsence/src/utilization/dto/response/participation/UserParticipationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/participation/ParticipationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
Labels: feature, review-needed

#289 관리자 예약 리스트 정렬기준 수정
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
Labels: fix, review-needed

#294 가게 정보 설정 관련 추가 설정 및 어드민이 소유한 가게 리스트 무한스크롤 적용
  src/main/java/project/seatsence/src/store/api/admin/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreMemberRepository.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: feature

#296 특정 스페이스와 날짜의 유효한 이용 시간 조회 API 구현
  src/main/java/project/seatsence/src/admin/dao/AdminInfoRepository.java
  src/main/java/project/seatsence/src/admin/domain/AdminInfo.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/utilization/api/UserUtilizationApi.java
  src/main/java/project/seatsence/src/utilization/api/UtilizationApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/UtilizationRepository.java
  src/main/java/project/seatsence/src/utilization/dao/UtilizationRepositoryCustom.java
  src/main/java/project/seatsence/src/utilization/dao/UtilizationRepositoryImpl.java
  src/main/java/project/seatsence/src/utilization/dao/walkin/WalkInRepository.java
  src/main/java/project/seatsence/src/utilization/dto/response/AllUtilizationsForSeatAndDateResponse.java
  src/main/java/project/seatsence/src/utilization/dto/response/reservation/AllReservationsForSeatAndDateResponse.java
  src/main/java/project/seatsence/src/utilization/service/UserUtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/UtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/WalkInService.java
Labels: feature, review-needed

#298 유저 스페이스 참여 API
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/utilization/api/participation/ParticipationApi.java
  src/main/java/project/seatsence/src/utilization/dao/participation/ParticipationRepository.java
  src/main/java/project/seatsence/src/utilization/dao/participation/ParticipationRepositoryCustom.java
  src/main/java/project/seatsence/src/utilization/dao/participation/ParticipationRepositoryImpl.java
  src/main/java/project/seatsence/src/utilization/domain/Participation/Participation.java
  src/main/java/project/seatsence/src/utilization/domain/walkin/WalkIn.java
  src/main/java/project/seatsence/src/utilization/dto/request/participation/UserParticipationRequest.java
  src/main/java/project/seatsence/src/utilization/service/participation/ParticipationService.java
Labels: feature, review-needed

#299 유저 참여 API HTTP 메서드 POST로 변경
  src/main/java/project/seatsence/src/utilization/api/participation/ParticipationApi.java
Labels: hotfix, review-needed

#300 특정 의자와 날짜의 바로 사용 중이거나 예약된 시간 조회 API 로직 수정
  src/main/java/project/seatsence/src/utilization/api/UserUtilizationApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/service/UserUtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/WalkInService.java
Labels: feature

#303 유저 의자/스페이스 바로 사용 API에서 Utilization 테이블에도 해당 데이터가 담기도록 로직 추가
  src/main/java/project/seatsence/src/utilization/domain/Utilization.java
  src/main/java/project/seatsence/src/utilization/service/UserUtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/UtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
Labels: feature

#305 바로사용인 스페이스 참여 시 '이용' 테이블에 데이터가 저장되는 로직 추가
  src/main/java/project/seatsence/src/utilization/service/participation/ParticipationService.java
Labels: feature, review-needed
