Repository seat-checking/back-end, pull requests merged in 2023-08, with the labels that each got.

#122 정상적인 예약 시간도 예외로 처리되는 버그 해결
  src/main/java/project/seatsence/src/reservation/api/UserReservationApi.java
  src/main/java/project/seatsence/src/reservation/service/ReservationService.java
  src/main/java/project/seatsence/src/reservation/service/UserReservationService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: bug, fix, review-needed

#129 CORS 해결을 위해 Security 설정 일부 수정 및 노출 Cookie명 변경
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/config/security/SpringSecurityConfig.java
Labels: bug

#132 SSL 설정
  .gitignore
  src/main/resources/application.yml
Labels: chore

#133 SSL 적용 완료 및 refreshToken 사용을 위한 Cookie 설정 변경
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/global/constants/Constants.java
  src/main/java/project/seatsence/global/utils/CookieUtils.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/user/service/UserService.java
  src/main/resources/application.yml
Labels: chore

#130 관리자의 예약 승인, 거절 기능 API
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/reservation/api/AdminReservationApi.java
  src/main/java/project/seatsence/src/reservation/domain/Reservation.java
  src/main/java/project/seatsence/src/reservation/service/AdminReservationService.java
Labels: feature

#134 Swagger에 JWT 인증 설정
  src/main/java/project/seatsence/global/config/SwaggerConfig.java
Labels: enhancement, chore

#138 springdoc.version missing bug 해결
  src/main/java/project/seatsence/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: bug

#137 유저 예약 현황 조회 기능 구현 및 Reservation class에 Store엔티티 추가와 이에 따른 로직 추가
  src/main/java/project/seatsence/global/response/SliceResponse.java
  src/main/java/project/seatsence/src/reservation/api/UserReservationApi.java
  src/main/java/project/seatsence/src/reservation/dao/ReservationRepository.java
  src/main/java/project/seatsence/src/reservation/domain/Reservation.java
  src/main/java/project/seatsence/src/reservation/domain/ReservationStatus.java
  src/main/java/project/seatsence/src/reservation/dto/request/SeatReservationRequest.java
  src/main/java/project/seatsence/src/reservation/dto/request/SpaceReservationRequest.java
  src/main/java/project/seatsence/src/reservation/dto/response/UserReservationListResponse.java
  src/main/java/project/seatsence/src/reservation/service/UserReservationService.java
Labels: enhancement, feature, chore, review-needed

#142 유저 좌석 예약 취소 기능 구현 완료 및 유저 스페이스 예약 취소 기능 일부 구현
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/reservation/api/UserReservationApi.java
  src/main/java/project/seatsence/src/reservation/dao/ReservationRepository.java
  src/main/java/project/seatsence/src/reservation/domain/Reservation.java
  src/main/java/project/seatsence/src/reservation/dto/response/UserReservationListResponse.java
  src/main/java/project/seatsence/src/reservation/service/ReservationService.java
  src/main/java/project/seatsence/src/reservation/service/UserReservationService.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
Labels: feature

#144 기획 변경에 따른, 유저 예약 취소 API쪽 로직 통합
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/reservation/api/UserReservationApi.java
  src/main/java/project/seatsence/src/reservation/service/UserReservationService.java
Labels: fix

#145 관리자 가게 예약 내역 리스트 API
  src/main/java/project/seatsence/src/reservation/api/AdminReservationApi.java
  src/main/java/project/seatsence/src/reservation/dao/ReservationRepository.java
  src/main/java/project/seatsence/src/reservation/dto/ReservationMapper.java
  src/main/java/project/seatsence/src/reservation/dto/response/ReservationListResponse.java
  src/main/java/project/seatsence/src/reservation/service/AdminReservationService.java
Labels: feature

#147 관리자 소유 가게 정보 조회시 유저 토큰값 사용
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dto/response/AdminOwnedStoreResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: fix, review-needed

#149 CROS환경에서 Header에 보이는 값 설정
  src/main/java/project/seatsence/global/config/security/CorsConfig.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
Labels: bug

#153 Refresh Token이 재발급될 때, 재발급 된 Referesh Token으로 교체되지않는 이슈 해결
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
Labels: bug

#154 reservation과 use 통합 관리를 위한 패키지 구조 변경과 특정 좌석 및 스페이스, 그리고 날짜에 따른 예약 현황 조회 응답 클래스 생성
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/reservation/Reservation.java
  src/main/java/project/seatsence/src/utilization/domain/reservation/ReservationStatus.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/ReservationMapper.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/SeatReservationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/SpaceReservationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/AllReservationsForSeatAndDateResponse.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/ReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
Labels: feature, refactoring

#156 유저 예약 현황 조회 API에서 PathVariable로 user-id를 받고있는 부분, JWT를 사용하도록 수정
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/service/UserService.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
  src/test/java/project/seatsence/src/store/service/StoreServiceTest.java
Labels: fix

#158 유저 예약 현황 API의 응답값 수정 - 이미지 필드 추가 및 예약한 좌석의 관리id나 스페이스명이 한 변수로 관리되게 수정
  src/main/java/project/seatsence/global/response/SliceResponse.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
Labels: enhancement

#163 storeSpace명이 조회되지않는 NPE 해결 및 필드와 데이터에서 예약된 정보와 관리 정보의 명확한 구분을 위해 필드(컬럼)명 수정
  src/main/java/project/seatsence/src/user/service/UserService.java
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/reservation/Reservation.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/ReservationMapper.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
Labels: bug, fix

#165 UserService의 method 이름 변경에 따른 호출 이름 수정
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: bug, review-needed

#167 관리자 로그인 시 메인 store의 우선순위 반영 및 관련 응답 추가
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminSignInResponse.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/dao/StoreMemberRepository.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
Labels: enhancement, review-needed

#171 유저 예약 현황 API에 닉네임 필드 추가 및 페이징 사이즈 조정
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
Labels: enhancement

#169 특정 좌석과 날짜에 대한 모든 예약 조회 API 구현 완료
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/reservation/Reservation.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/ReservationMapper.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/AllReservationsForChairAndDateRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/SeatReservationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/SpaceReservationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/AllReservationsForChairAndDateResponse.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/AllReservationsForSeatAndDateResponse.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/ReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
Labels: feature, review-needed

#176 예약 취소 API에서 승인된 예약에 대해서도 취소가 가능하도록 로직 추가
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
Labels: enhancement

#178 관리자 및 직원의 가게 별 권한 확인 API
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreMemberRepository.java
  src/main/java/project/seatsence/src/store/domain/StoreMember.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStorePermissionResponse.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/ReservationMapper.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/AdminReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
Labels: feature, review-needed

#180 회원가입 시 입력 받던 나이를 생년월일로 교체
  src/main/java/project/seatsence/global/annotation/ValidBirthDate.java
  src/main/java/project/seatsence/global/annotation/validator/BirthDateValidator.java
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignUpRequest.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/user/domain/User.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignInRequest.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignUpRequest.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: fix

#183 관리자 회원가입 및 가게 추가 시, 가게 위치를 바로 입력 받게 수정
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignUpRequest.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminNewBusinessInformationRequest.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: fix, review-needed

#187 한번에 입력 받던 가게의 주소를 address와 detailAddress로 분리
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignUpRequest.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminNewBusinessInformationRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreBasicInformationRequest.java
  src/main/java/project/seatsence/src/store/dto/response/StoreListResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: fix, review-needed

#192 user 그리고 본인이 담당한 reservation의 일부에서 요청값으로 user식별자 받고있는 부분은 JWT사용하도록 수정 및 Swagger관련 코드 추가
  src/main/java/project/seatsence/src/admin/dto/request/AdminSignInRequest.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dto/request/FindUserByEmailRequest.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignInRequest.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignUpRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateEmailRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateNicknameRequest.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/AllReservationsForSeatAndDateRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/ChairReservationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/request/SpaceReservationRequest.java
Labels: enhancement

#195 유저 예약 현황 조회 API에서 예약 상태가 '대기'인 데이터의 예약 끝 일정이 현 시간을 지났을 경우 '거절'로 바뀌도록 로직 추가 및 Reservation쪽 Service에서 Repository를 직접 사용하지 않도록 리팩토링
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/ReservationService.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
Labels: enhancement, refactoring, review-needed

#194 가게 스페이스 api 분리
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreRepository.java
  src/main/java/project/seatsence/src/store/domain/Category.java
  src/main/java/project/seatsence/src/store/domain/StoreSpace.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceCreateRequest.java
  src/main/java/project/seatsence/src/store/dto/response/AdminOwnedStoreResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreFormResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceSeatResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/test/java/project/seatsence/SeatSenceApplicationTests.java
Labels: feature, review-needed

#193 관리자 가게의 원하는 예약 정보 커스텀 API
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreCustomRepository.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationContent.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationField.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationFieldType.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreReservationFieldCustomRequest.java
  src/main/java/project/seatsence/src/store/service/StoreCustomService.java
Labels: feature, review-needed

#199 관리자 가게의 예약 리스트 응답값 및 필드명 수정
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/ReservationMapper.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/AdminReservationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
Labels: fix, review-needed

#201 Token을 활용하는 API에서 토큰 재발급 받을 때 500응답 받는 이슈 해결
  build.gradle
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
Labels: bug, refactoring

#202 관리자 가게의 예약 정보 커스텀 시 리스트로 여러 항목 입력 가능하게 수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationFieldType.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreCustomReservationFieldRequest.java
  src/main/java/project/seatsence/src/store/service/StoreCustomService.java
Labels: fix, review-needed

#203 예약 정보 커스텀 필드의 타입 이름수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationFieldType.java
Labels: fix, review-needed

#206 가게 스페이스별 좌석 수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreChairRepository.java
  src/main/java/project/seatsence/src/store/dao/StoreTableRepository.java
  src/main/java/project/seatsence/src/store/domain/StoreSpace.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceUpdateRequest.java
  src/main/java/project/seatsence/src/store/dto/response/AdminOwnedStoreResponse.java
  src/main/java/project/seatsence/src/store/service/StoreChairService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/main/java/project/seatsence/src/store/service/StoreTableService.java
Labels: feature, review-needed

#210 운영시간 및 임시휴업 설정 기획 변경에 따른 운영중, 임시휴업 응답 데이터 수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreTemporaryClosedRequest.java
  src/main/java/project/seatsence/src/store/dto/response/AdminOwnedStoreResponse.java
  src/main/java/project/seatsence/src/store/dto/response/StoreListResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: fix, review-needed

#209 가게 임시휴업 여부 설정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreTemporaryClosedRequest.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: feature, review-needed

#214 관리자 가게의 예약 필드 커스텀 리스트, 수정, 삭제 API
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/global/entity/BaseTimeAndStateEntity.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreCustomRepository.java
  src/main/java/project/seatsence/src/store/domain/CustomReservationField.java
  src/main/java/project/seatsence/src/store/dto/CustomReservationFieldMapper.java
  src/main/java/project/seatsence/src/store/dto/request/StoreCustomReservationFieldRequest.java
  src/main/java/project/seatsence/src/store/dto/response/StoreCustomReservationFieldListResponse.java
  src/main/java/project/seatsence/src/store/service/StoreCustomService.java
Labels: feature

#213 어드민 스페이스 응답 형태 및 필드 이름 수정
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreWifiRepository.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/domain/StoreChair.java
  src/main/java/project/seatsence/src/store/domain/StoreSpace.java
  src/main/java/project/seatsence/src/store/domain/StoreTable.java
  src/main/java/project/seatsence/src/store/domain/StoreWifi.java
  src/main/java/project/seatsence/src/store/dto/AdminStoreMapper.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreIsClosedTodayRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceChairRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceCreateRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceTableRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceUpdateRequest.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreTemporaryClosedRequest.java
  src/main/java/project/seatsence/src/store/dto/request/ReservationUnitRequest.java
  src/main/java/project/seatsence/src/store/dto/response/AdminOwnedStoreResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceChairResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceCreateResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceSeatResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceTableResponse.java
  src/main/java/project/seatsence/src/store/dto/response/ReservationUnitResponse.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
  src/main/java/project/seatsence/src/utilization/dto/reservation/response/UserReservationListResponse.java
Labels: fix

#217 관리자 가게 예약 리스트의 내림차순 정렬 및 무한스크롤 적용
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
  src/main/java/project/seatsence/src/utilization/dao/reservation/ReservationRepository.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
Labels: enhancement, fix

#219 유저 검색 API 수정 및 직원 등록 시 에러코드 수정
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/admin/service/AdminService.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dto/CustomReservationFieldMapper.java
  src/main/java/project/seatsence/src/store/dto/response/StoreCustomReservationFieldListResponse.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dao/UserRepository.java
  src/main/java/project/seatsence/src/user/dto/response/FindUserByEmailResponse.java
  src/main/java/project/seatsence/src/user/service/UserService.java
Labels: fix, refactoring, review-needed

#222 관리자 로그인 응답에 필드 추가
  src/main/java/project/seatsence/src/admin/api/AdminApi.java
  src/main/java/project/seatsence/src/admin/dto/response/AdminSignInResponse.java
  src/main/java/project/seatsence/src/utilization/api/reservation/AdminReservationApi.java
Labels: fix, review-needed

#225 store chair manageId 저장 안되는 에러 해결
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceCreateRequest.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: fix, review-needed

#228 가게 기본정보, 운영시간정보 받아오는 API 분리
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dto/AdminStoreMapper.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreBasicInformationResponse.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreOperatingTimeResponse.java
Labels: feature

#232 가게 오늘 영업 중단 여부(isCloseToday) 변경 반영 안되는 에러 해결
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreIsClosedTodayRequest.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: bug, review-needed

#230 다른 가게에 등록 되어있는 직원도 등록 가능하게 수정
  src/main/java/project/seatsence/src/store/dao/StoreMemberRepository.java
  src/main/java/project/seatsence/src/store/service/StoreMemberService.java
Labels: fix, review-needed

#234 스페이스 바로 사용 API 구현 및 좌석 바로 사용 API 리팩토링
  src/main/java/project/seatsence/global/config/filter/JwtFilter.java
  src/main/java/project/seatsence/global/config/handler/CustomAuthSuccessHandler.java
  src/main/java/project/seatsence/global/config/security/JwtProvider.java
  src/main/java/project/seatsence/src/user/service/UserService.java
  src/main/java/project/seatsence/src/utilization/api/walkin/UserWalkInApi.java
  src/main/java/project/seatsence/src/utilization/domain/Utilization.java
  src/main/java/project/seatsence/src/utilization/service/UserUtilizationService.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
Labels: feature, refactoring, review-needed

#233 이용 중인 좌석 또는 스페이스 강제 퇴실 기능 API
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/utilization/api/AdminUtilizationApi.java
  src/main/java/project/seatsence/src/utilization/dao/UtilizationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/Utilization.java
  src/main/java/project/seatsence/src/utilization/service/AdminUtilizationService.java
Labels: feature

#237 관리자 예약 현황 리스트의 예약 내역이 없는 경우 응답 코드를 성공으로 수정
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
Labels: fix

#240 가게 운영시간 설정 안되어있을 때 조회 에러 해결
  src/main/java/project/seatsence/global/utils/EnumUtils.java
  src/main/java/project/seatsence/src/store/dto/response/AdminStoreBasicInformationResponse.java
  src/main/java/project/seatsence/src/utilization/service/reservation/AdminReservationService.java
Labels: bug, review-needed

#242 가게 기본 정보 등록 시 이미지 업로드
  build.gradle
  src/main/java/project/seatsence/global/config/S3Config.java
  src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreImageRepository.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/domain/StoreImage.java
  src/main/java/project/seatsence/src/store/dto/request/AdminStoreBasicInformationRequest.java
  src/main/java/project/seatsence/src/store/service/S3Service.java
  src/main/java/project/seatsence/src/store/service/StoreImageService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/resources/application.yml
Labels: feature, review-needed
