Repository seat-checking/back-end, pull requests merged in 2023-09, with the labels that each got.

#251 서버 실행에러 해결
  src/main/java/project/seatsence/src/store/api/UserStoreTempApi.java
  src/main/java/project/seatsence/src/store/domain/ReservationUnit.java
Labels: hotfix

#254 가게 정보 조회 시 이미지 링크 같이 내려주기
  src/main/java/project/seatsence/src/store/api/admin/AdminStoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreImageRepository.java
  src/main/java/project/seatsence/src/store/domain/StoreImage.java
  src/main/java/project/seatsence/src/store/dto/response/admin/basic/StoreBasicInformationResponse.java
  src/main/java/project/seatsence/src/store/service/StoreImageService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: feature, review-needed

#259 ec2 서버시간 한국시간으로 변경
  src/main/java/project/seatsence/SeatSenceApplication.java
Labels: fix, review-needed

#263 유저 이용현황 바로사용 리스트 API
  src/main/java/project/seatsence/src/store/dao/StoreMemberRepository.java
  src/main/java/project/seatsence/src/utilization/api/walkin/UserWalkInApi.java
  src/main/java/project/seatsence/src/utilization/dao/walkin/WalkInRepository.java
  src/main/java/project/seatsence/src/utilization/dto/response/walkin/UserWalkInListResponse.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
Labels: feature, review-needed

#265 유저 바로 사용 리스트 응답 및 에러코드 수정
  src/main/java/project/seatsence/src/utilization/dto/response/walkin/UserWalkInListResponse.java
  src/main/java/project/seatsence/src/utilization/service/walkin/UserWalkInService.java
Labels: fix, review-needed

#266 가게 좌석 통계정보 조회 API 구현
  src/main/java/project/seatsence/src/holding/domain/Holding.java
  src/main/java/project/seatsence/src/holding/domain/HoldingStatus.java
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/dao/StoreChairRepository.java
  src/main/java/project/seatsence/src/store/dao/StoreSpaceRepository.java
  src/main/java/project/seatsence/src/store/domain/Store.java
  src/main/java/project/seatsence/src/store/domain/StoreChair.java
  src/main/java/project/seatsence/src/store/domain/StoreTable.java
  src/main/java/project/seatsence/src/store/dto/response/LoadSeatStatisticsInformationOfStoreResponse.java
  src/main/java/project/seatsence/src/store/service/StoreChairService.java
  src/main/java/project/seatsence/src/store/service/StoreService.java
  src/main/java/project/seatsence/src/utilization/dao/UtilizationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/Utilization.java
  src/main/java/project/seatsence/src/utilization/domain/UtilizationStatus.java
  src/main/java/project/seatsence/src/utilization/domain/reservation/Reservation.java
  src/main/java/project/seatsence/src/utilization/domain/walkin/WalkIn.java
  src/main/java/project/seatsence/src/utilization/dto/response/LoadSeatsCurrentlyInUseResponse.java
  src/main/java/project/seatsence/src/utilization/service/UtilizationService.java
Labels: feature, review-needed

#268 GET 요청은 RequestBody를 사용하지 않도록 수정
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dto/request/reservation/AllReservationsForSeatAndDateRequest.java
  src/main/java/project/seatsence/src/utilization/service/reservation/UserReservationService.java
Labels: bug, review-needed

#269 유저 이용현황의 스페이스 참여 리스트 API
  src/main/java/project/seatsence/src/utilization/api/participation/ParticipationApi.java
  src/main/java/project/seatsence/src/utilization/dao/participation/ParticipationRepository.java
  src/main/java/project/seatsence/src/utilization/domain/Participation/Participation.java
  src/main/java/project/seatsence/src/utilization/domain/Participation/ParticipationStatus.java
  src/main/java/project/seatsence/src/utilization/dto/response/participation/ParticipationListResponse.java
  src/main/java/project/seatsence/src/utilization/service/participation/ParticipationService.java
Labels: feature

#271 유저 스페이스 참여 취소 API
  src/main/java/project/seatsence/global/code/ResponseCode.java
  src/main/java/project/seatsence/src/utilization/api/participation/ParticipationApi.java
  src/main/java/project/seatsence/src/utilization/domain/Participation/Participation.java
  src/main/java/project/seatsence/src/utilization/domain/Participation/ParticipationStatus.java
  src/main/java/project/seatsence/src/utilization/service/participation/ParticipationService.java
Labels: feature

#274 가게 스페이스 정보 응답 필드 변경 및 api 위치 수정
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/store/api/admin/StoreSpaceApi.java
  src/main/java/project/seatsence/src/store/dto/response/admin/space/StoreSpaceChairResponse.java
  src/main/java/project/seatsence/src/store/dto/response/admin/space/StoreSpaceTableResponse.java
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: feature

#277 Swagger관련 설정 중 name 값 삭제
  src/main/java/project/seatsence/src/store/api/StoreApi.java
  src/main/java/project/seatsence/src/user/api/UserApi.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignInRequest.java
  src/main/java/project/seatsence/src/user/dto/request/UserSignUpRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateEmailRequest.java
  src/main/java/project/seatsence/src/user/dto/request/ValidateNicknameRequest.java
  src/main/java/project/seatsence/src/utilization/api/UtilizationApi.java
  src/main/java/project/seatsence/src/utilization/api/reservation/UserReservationApi.java
  src/main/java/project/seatsence/src/utilization/dto/request/ChairUtilizationRequest.java
  src/main/java/project/seatsence/src/utilization/dto/request/SpaceUtilizationRequest.java
Labels: chore

#281 가게 기본 정보 수정 시 image가 없을때 null pointer exception 버그 해결
  src/main/java/project/seatsence/src/store/service/StoreService.java
Labels: hotfix

#282 Table, Chair에 Store 속성 추가됨에 따라 builder 필드 추가
  src/main/java/project/seatsence/src/store/service/StoreSpaceService.java
Labels: hotfix
